name: Setup Golang
description: Configures Golang with caching

runs:
  using: "composite"

  steps:
    # uses the go version from go.mod.
    # Run this step after the checkout step!
    - name: Setup Golang
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: "go.mod"
        cache: true

    - name: Install Tools
      shell: bash
      run: make install-tools
