version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustruct
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gocognit
    - gocritic
    - gomoddirectives
    - gosec
    - importas
    - inamedparam
    - ireturn
    - lll
    - maintidx
    - nestif
    - nlreturn
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - promlinter
    - sqlclosecheck
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 80
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: kcorev1
        - pkg: k8s.io/api/apps/v1
          alias: kappsv1
        - pkg: k8s.io/api/rbac/v1
          alias: krbacv1
        - pkg: k8s.io/apimachinery/pkg/runtime/schema
          alias: kschema
        - pkg: k8s.io/apimachinery/pkg/labels
          alias: klabels
        - pkg: k8s.io/apimachinery/pkg/runtime
          alias: kruntime
        - pkg: k8s.io/apimachinery/pkg/types
          alias: ktypes
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
          alias: kunstructured
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: kmetav1
        - pkg: k8s.io/client-go/dynamic/fake
          alias: kdynamicfake
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
          alias: kapixclientset
        - pkg: k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake
          alias: kapixclientsetfake
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: kerrors
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: kapiextensionsv1
        - pkg: sigs.k8s.io/controller-runtime
          alias: kctrl
        - pkg: sigs.k8s.io/controller-runtime/pkg/log
          alias: kctrllog
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: kctrlclient
        - pkg: k8s.io/api/autoscaling/v1
          alias: kautoscalingv1
        - pkg: k8s.io/api/autoscaling/v2
          alias: kautoscalingv2
        - pkg: k8s.io/api/admissionregistration/v1
          alias: kadmissionregistrationv1
        - pkg: istio.io/client-go/pkg/apis/security/v1beta1
          alias: istiopkgsecurityv1beta1
        - pkg: istio.io/api/(\w+)/(v\d+\w*\d*)$
          alias: istio$1$2
        - pkg: github.com/kyma-project/kyma/common/logging/logger
          alias: kymalogger
        - pkg: github.com/onsi/gomega/types
          alias: gomegatypes
        - pkg: k8s.io/apimachinery/pkg/util/runtime
          alias: kutilruntime
        - pkg: k8s.io/client-go/kubernetes/scheme
          alias: kkubernetesscheme
        - pkg: github.com/pkg/errors
          alias: pkgerrors
        - pkg: github.com/kyma-project/kyma-metrics-collector/pkg/otel
          alias: kmcotel
      no-unaliased: false
      no-extra-aliases: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - Client
        - client.Object
        - (or|er)$
    nestif:
      min-complexity: 6
    revive:
      severity: error
      enable-all-rules: false
      rules:
        - name: comment-spacings
          disabled: true
        - name: dot-imports
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
    varnamelen:
      ignore-names:
        - ok
        - g
        - a
        - b
        - tc
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-decls:
        - i int
        - g *gomega.WithT
        - w http.ResponseWriter
        - r *http.Request
        - cm *v1.ConfigMap
        - cm *kcorev1.ConfigMap
        - js JetStream
        - js *JetStream
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - maintidx
          - wrapcheck
        path: _test\.go
      - linters:
          - importas
        text: has alias "" which is not part of config
      - linters:
          - lll
        source: '^// +kubebuilder: '
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kyma-project/kyma-metrics-collector)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
