{{- if and (.Capabilities.APIVersions.Has "operator.victoriametrics.com/v1beta1/VMServiceScrape") .Values.vmscrapes.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
{{ include "kyma-metrics-collector.labels" . | indent 4 }}
  name: {{ include "kyma-metrics-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - attach_metadata: {}
      port: http
      interval: {{ .Values.vmscrapes.interval }}
      scrapeTimeout: {{ .Values.vmscrapes.scrapeTimeout }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
{{ include "kyma-metrics-collector.labels" . | indent 6 }}
{{- end }}
