name: All Checks passed
on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        ready_for_review,
        edited,
        labeled,
        milestoned,
      ]
  merge_group:
jobs:
  all-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - uses: wechuli/allcheckspassed@3c3c97b4f5dbe6c7652fc7c66bd1bed7886800d8
        with:
          retries: '40'
          polling_interval: '1'
